version: '2'
services:
    redis:
        image: 'redis:3.2.7'

    postgres:
        image: postgres:9.6
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: lukealexmiller/docker-airflow-gpu:1.8.1
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=hBz78Go3mJRJoHsD7Hsv6u7mu0Q4x74IYbMUhlZ1avI=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
        volumes:
#            - nvidia_driver:/usr/local/nvidia/:ro
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
            - ./hdd:/usr/local/airflow/hdd
            - syno_raw_data:/usr/local/airflow/syno/raw_data
            - syno_anon_data:/usr/local/airflow/syno/anon_data
            - tmp:/usr/local/airflow/server
        ports:
            - "8080:8080"
        command: webserver

    flower:
        image: lukealexmiller/docker-airflow-gpu:1.8.1
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: lukealexmiller/docker-airflow-gpu:1.8.1
        restart: always
        depends_on:
            - webserver
        volumes:
#            - nvidia_driver:/usr/local/nvidia/:ro
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
            - ./hdd:/usr/local/airflow/hdd
            - syno_raw_data:/usr/local/airflow/syno/raw_data
            - syno_anon_data:/usr/local/airflow/syno/anon_data
            - tmp:/usr/local/airflow/server
        environment:
            - LOAD_EX=n
            - FERNET_KEY=hBz78Go3mJRJoHsD7Hsv6u7mu0Q4x74IYbMUhlZ1avI=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
        command: scheduler

    worker:
        image: lukealexmiller/docker-airflow-gpu:1.8.1
        restart: always
        depends_on:
            - scheduler
        volumes:
#            - nvidia_driver:/usr/local/nvidia/:ro
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
            - ./hdd:/usr/local/airflow/hdd
            - syno_raw_data:/usr/local/airflow/syno/raw_data
            - syno_anon_data:/usr/local/airflow/syno/anon_data
            - tmp:/usr/local/airflow/server
            - ./weights:/usr/local/airflow/faster_rcnn/weights
        environment:
            - FERNET_KEY=hBz78Go3mJRJoHsD7Hsv6u7mu0Q4x74IYbMUhlZ1avI=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
        command: worker

volumes:
    db-data:
        driver: local
    syno_raw_data: 
        driver: cifs
        driver_opts:
            share:  syno.fritz.box/raw_data       
    syno_anon_data: 
        driver: cifs
        driver_opts:
            share:  syno.fritz.box/anon_data
    tmp:
        driver: local
