version: '2'
services:
    redis:
        image: 'redis:3.2.7'

    postgres:
        image: postgres:9.6
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: lukealexmiller/docker-airflow:1.8.1
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=hBz78Go3mJRJoHsD7Hsv6u7mu0Q4x74IYbMUhlZ1avI=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
            - ./hdd:/usr/local/airflow/hdd
            - ./syno:/usr/local/airflow/syno
            - ./server:/usr/local/airflow/server
        ports:
            - "8080:8080"
        command: webserver

    flower:
        image: lukealexmiller/docker-airflow:1.8.1
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: lukealexmiller/docker-airflow:1.8.1
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
            - ./hdd:/usr/local/airflow/hdd
            - ./syno:/usr/local/airflow/syno
            - ./server:/usr/local/airflow/server
        environment:
            - LOAD_EX=n
            - FERNET_KEY=hBz78Go3mJRJoHsD7Hsv6u7mu0Q4x74IYbMUhlZ1avI=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
        command: scheduler

    worker:
        image: lukealexmiller/docker-airflow:1.8.1
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
            - ./hdd:/usr/local/airflow/hdd
            - ./syno:/usr/local/airflow/syno
            - ./server:/usr/local/airflow/server
        environment:
            - FERNET_KEY=hBz78Go3mJRJoHsD7Hsv6u7mu0Q4x74IYbMUhlZ1avI=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
        command: worker

volumes:
    db-data:
        driver: local