services:
  flower:
    command: flower
    depends_on:
    - redis
    devices:
    - /dev/nvidia0
    - /dev/nvidia1
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    environment:
    - EXECUTOR=Celery
    image: lukealexmiller/docker-airflow-gpu:1.8.1
    ports:
    - 5555:5555
    restart: always
    volumes:
    - nvidia_driver_375.66:/usr/local/nvidia:ro
  postgres:
    devices:
    - /dev/nvidia0
    - /dev/nvidia1
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    environment:
    - POSTGRES_USER=airflow
    - POSTGRES_PASSWORD=airflow
    - POSTGRES_DB=airflow
    image: postgres:9.6
    volumes:
    - db-data:/var/lib/postgresql/data
    - nvidia_driver_375.66:/usr/local/nvidia:ro
  redis:
    devices:
    - /dev/nvidia0
    - /dev/nvidia1
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    image: redis:3.2.7
    volumes:
    - nvidia_driver_375.66:/usr/local/nvidia:ro
  scheduler:
    command: scheduler
    depends_on:
    - webserver
    devices:
    - /dev/nvidia0
    - /dev/nvidia1
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    environment:
    - LOAD_EX=n
    - FERNET_KEY=hBz78Go3mJRJoHsD7Hsv6u7mu0Q4x74IYbMUhlZ1avI=
    - EXECUTOR=Celery
    image: lukealexmiller/docker-airflow-gpu:1.8.1
    restart: always
    volumes:
    - ./dags:/usr/local/airflow/dags
    - ./plugins:/usr/local/airflow/plugins
    - ./hdd:/usr/local/airflow/hdd
    - syno_raw_data:/usr/local/airflow/syno/raw_data
    - syno_anon_data:/usr/local/airflow/syno/anon_data
    - tmp:/usr/local/airflow/server
    - nvidia_driver_375.66:/usr/local/nvidia:ro
  webserver:
    command: webserver
    depends_on:
    - postgres
    - redis
    devices:
    - /dev/nvidia0
    - /dev/nvidia1
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    environment:
    - LOAD_EX=n
    - FERNET_KEY=hBz78Go3mJRJoHsD7Hsv6u7mu0Q4x74IYbMUhlZ1avI=
    - EXECUTOR=Celery
    image: lukealexmiller/docker-airflow-gpu:1.8.1
    ports:
    - 8080:8080
    restart: always
    volumes:
    - ./dags:/usr/local/airflow/dags
    - ./plugins:/usr/local/airflow/plugins
    - ./hdd:/usr/local/airflow/hdd
    - syno_raw_data:/usr/local/airflow/syno/raw_data
    - syno_anon_data:/usr/local/airflow/syno/anon_data
    - tmp:/usr/local/airflow/server
    - nvidia_driver_375.66:/usr/local/nvidia:ro
  worker:
    command: worker
    depends_on:
    - scheduler
    devices:
    - /dev/nvidia0
    - /dev/nvidia1
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    environment:
    - FERNET_KEY=hBz78Go3mJRJoHsD7Hsv6u7mu0Q4x74IYbMUhlZ1avI=
    - EXECUTOR=Celery
    image: lukealexmiller/docker-airflow-gpu:1.8.1
    restart: always
    volumes:
    - ./dags:/usr/local/airflow/dags
    - ./plugins:/usr/local/airflow/plugins
    - ./hdd:/usr/local/airflow/hdd
    - syno_raw_data:/usr/local/airflow/syno/raw_data
    - syno_anon_data:/usr/local/airflow/syno/anon_data
    - tmp:/usr/local/airflow/server
    - ./weights:/usr/local/airflow/faster_rcnn/weights
    - nvidia_driver_375.66:/usr/local/nvidia:ro
version: '2'
volumes:
  db-data:
    driver: local
  nvidia_driver_375.66:
    external: true
  syno_anon_data:
    driver: cifs
    driver_opts:
      share: syno.fritz.box/anon_data
  syno_raw_data:
    driver: cifs
    driver_opts:
      share: syno.fritz.box/raw_data
  tmp:
    driver: local
